apiVersion: apps/v1
kind: Deployment
metadata:
  name: retrieve-usagedata
spec:
  selector:
    matchLabels:
      app: retrieve-usagedata
  replicas: 1
  template:
    metadata:
      labels:
        app: retrieve-usagedata
    spec:
      containers:
      - name: retrieve-usagedata
        image: kos-cluster.icp:8500/sit-kos/retrieve-usagedata:0.1
        args: ["-Dspring.redis.host=redis -Dspring.redis.port=6379"]
        ports:
        - containerPort: 8080
