apiVersion: v1
kind: Service
metadata:
  name: retrieve-usagedata-svc
  labels:
    app: retrieve-usagedata
spec:
  ports:
  - name: retrieve-usagedata
    port: 80
    targetPort: 8080
  type: NodePort
  selector:
    app: retrieve-usagedata
